### PR TITLE
Adding ability to specify a delimiter during table creation

### PR DESCRIPTION
**Pull request by jithinjohn**

### CODE REVIEW

**Comment by jagatsingh** [comment]
@jithinjohn allowing multiple delimiters? 

Yes

Then read documentation a bit

No

Then define as char instead of string

**Comment by jagatsingh** [comment]
There was some regex thing for multidelimiter I forgot now just read once

**Comment by jithinjohn** [comment]
@jagatsingh This is to address the issue #114

**Comment by jithinjohn** [comment]
@rowandavies Have done the changes. Are you happy to merge?

**Comment by rowandavies** [comment]
Yes, go ahead and merge.  My earlier message with the :+1: indicated that I was happy for you to merge after you'd dealt with the minor issues.

**Pull request merged**
