### PR TITLE
Closes #82.

### LINKED ISSUE #82: PartitionHiveParquetScroogeSource can't read from data written by PartitionHiveParquetScroogeSink
See
https://github.com/CommBank/bureaucracy/commit/fc6c4a8e4505dd01ad68c8e8d9e0bbf313487082#commitcomment-9790295
for some more background.

### PR DESCRIPTION
**Pull request by RayRoestenburg**

### CODE REVIEW

**Comment by RayRoestenburg** [comment]
@stephanh can I merge this into CDH5 branch? what do you think? /cc @laurencer

**Comment by laurencer** [comment]
LGTM :+1: - @stephanh thoughts?

**Comment by stephanh** [comment]
Sorry I have been too busy with the CDH5 upgrade to look at this. If I look at this by Thursday is that still ok?

Really sorry about the delay @RayRoestenburg just been too busy with other stuff to really understand this.

Some questions I have are:
* Why merge this into CDH5 and not master?
* Is the behaviour different using local tests vs on cluster tests? I tried just changing `setStringPath` and thought it worked but I didn't look into it enough to be certain.

**Comment by RayRoestenburg** [comment]
Hi @stephanh Thursday is fine I can work with a local build for now. No worries I heard you're busy :-) 
I haven't tried cluster tests, is there a special test suite for that (any tips how to try it out on the cluster will really help). It can be merged in master as well, I specifically need a version for CDH5 for my project at the moment (so would like the fix to go both into master and CDH5). The local test did not work with just changing setStringPath (unless I misunderstood the change you proposed) so please try that as well.

**Comment by stephanh** [comment]
Closing this in favour of #84 which takes your fix, tidies up the tests and puts the changes into master.

Once #84 is merged I will rebase the CDH5 branch on top of it.

Sorry again for the delay in responding to this. I thought I had a way where I could keep the identifiers as they originally were which would have been the standard way Cascading creates identifiers for Partitioned sources. However, I was not able to make that happen.

**Pull request closed without merging**
